name: 'Deploy'

on:
  workflow_run:
    workflows: ["Docker Image And Push to Registry"]
    types:
      - completed

jobs:
  deploy-api:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull mydockerid103017/ms-auth-spring-boot:latest

      - name: Stop Docker Container
        run: sudo docker stop ms-auth-app || true

      - name: Remove Docker Container
        run: sudo docker rm ms-auth-app || true

      - name: Run Docker Container
        run: sudo docker run --name ms-auth-app -d -p 8080:8080 mydockerid103017/ms-auth-spring-boot:latest