name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        id: build
        run: |
          docker build . --file Dockerfile --tag mydockerid103017/ms-auth-spring-boot:latest
          echo "image_tag=mydockerid103017/ms-auth-spring-boot:latest" >> $GITHUB_ENV

  push-to-registry:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.image_tag }}
