name: "Workflow Sandbox"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  docker-image:
    needs: [ build ]
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        id: build
        run: |
          docker build . --file Dockerfile --tag mydockerid103017/ms-auth-spring-boot:latest
          docker save mydockerid103017/ms-auth-spring-boot:latest -o ms-auth-spring-boot.tar

      - name: Upload image for push job
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ms-auth-spring-boot.tar

  push-image:
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Download image from build job
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i ms-auth-spring-boot.tar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push mydockerid103017/ms-auth-spring-boot:latest

  call-deploy-dev:
    environment: development
    needs: push-image
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull mydockerid103017/ms-auth-spring-boot:latest

      - name: Stop Docker Container
        run: sudo docker stop ms-auth-app || true

      - name: Remove Docker Container
        run: sudo docker rm ms-auth-app || true

      - name: Run Docker Container
        run: sudo docker run --name ms-auth-app -d -p 8080:8080 mydockerid103017/ms-auth-spring-boot:latest

      - name: Get Public IP Address
        id: get_ip
        run: |
          PUBLIC_IP=$(curl -s ifconfig.me)
          echo "Public IP Address: $PUBLIC_IP"
          echo "::set-output name=public_ip::$PUBLIC_IP"

      - name: Create README of Execution
        run: |
          echo "# Resumo da execução" > README.md
          echo "" >> README.md
          echo "## Deploy da Api" >> README.md
          echo "- **Public IP**: ${{ steps.get_ip.outputs.public_ip }}" >> README.md
          echo "- **API URL**: http://${{ steps.get_ip.outputs.public_ip }}:8080/api/ms-auth" >> README.md
          echo "" >> README.md

      - name: Upload README as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Deployment-README
          path: README.md